import os
import time


class ReportGenerator:
    # collects alerts during a run and writes a single html file at exit

    def __init__(self):
        self.filename = "mantis_report.html"
        self.alerts = []

    def add_alert(self, msg):
        self.alerts.append({"time": time.strftime("%H:%M:%S"), "message": msg})

    def generate(self):
        if not self.alerts:
            return  # nothing happened, skip

        rows = []
        for a in self.alerts:
            msg = a["message"]
            kind, css = "UNKNOWN", ""
            if "DDoS" in msg:
                kind, css = "DDoS Attack", "tag-ddos"
            elif "SCAN" in msg:
                kind, css = "Port Scan", "tag-scan"
            elif "PAYLOAD" in msg:
                kind, css = "Web Attack", "tag-web"
            elif "BLACKLIST" in msg:
                kind, css = "Blacklist Hit", "tag-malware"
            rows.append(
                "<tr><td>%s</td><td><span class='tag %s'>%s</span></td><td>%s</td></tr>"
                % (a["time"], css, kind, msg)
            )

        html = """<!DOCTYPE html>
<html><head><title>MANTIS Threat Report</title>
<style>
body{font-family:'Segoe UI',sans-serif;background:#1a1a1a;color:#f0f0f0;margin:0;padding:20px}
h1{color:#00ff9d;border-bottom:2px solid #00ff9d;padding-bottom:10px}
.card{background:#2d2d2d;border-radius:8px;padding:20px;margin-bottom:20px;
      box-shadow:0 4px 6px rgba(0,0,0,0.3)}
table{width:100%;border-collapse:collapse;margin-top:10px}
th,td{padding:12px;text-align:left;border-bottom:1px solid #404040}
th{background:#333;color:#00ff9d}
tr:hover{background:#383838}
.tag{padding:4px 8px;border-radius:4px;font-size:12px;font-weight:bold}
.tag-ddos{background:#ff4444;color:#fff}
.tag-scan{background:#ffbb33;color:#000}
.tag-web{background:#33b5e5;color:#fff}
.tag-malware{background:#aa66cc;color:#fff}
.summary-box{display:flex;gap:20px}
.metric{background:#333;padding:15px;border-radius:5px;flex:1;text-align:center}
.metric h3{margin:0;color:#888;font-size:14px}
.metric p{margin:5px 0 0;font-size:24px;font-weight:bold;color:#fff}
</style></head><body>
<h1>M.A.N.T.I.S. Forensic Report</h1>
<div class="card"><h2>Session Summary</h2>
  <div class="summary-box">
    <div class="metric"><h3>Generated At</h3><p>__GENERATED_AT__</p></div>
    <div class="metric"><h3>Total Alerts</h3><p>__ALERT_COUNT__</p></div>
    <div class="metric"><h3>System Status</h3><p style="color:#ff4444">COMPROMISED</p></div>
  </div>
</div>
<div class="card"><h2>Incident Log</h2>
<table><thead><tr><th>Time</th><th>Threat Type</th><th>Details</th></tr></thead>
<tbody>__ALERT_ROWS__</tbody></table>
</div>
<div class="card"><p>Generated by M.A.N.T.I.S.</p></div>
</body></html>"""
        html = (html
                .replace("__GENERATED_AT__", time.ctime())
                .replace("__ALERT_COUNT__", str(len(self.alerts)))
                .replace("__ALERT_ROWS__", "".join(rows)))

        with open(self.filename, "w") as f:
            f.write(html)
        print("\n[*] report written to", os.path.abspath(self.filename))


if __name__ == "__main__":
    r = ReportGenerator()
    r.add_alert("DDoS DETECTED! Z-Score: 5.2")
    r.add_alert("PORT SCAN DETECTED! (Unique Ports: 44/sec)")
    r.add_alert("MALICIOUS PAYLOAD! Keywords: ['UNION', 'SELECT']")
    r.generate()
