import time
import os
import json

# MANTIS Phase 6: Reporting Module
# Generates Professional HTML Forensics Reports

class ReportGenerator:
    def __init__(self):
        self.filename = "mantis_report.html"
        self.alerts = []
        
    def add_alert(self, alert_msg):
        """Adds an alert to the internal list with a timestamp."""
        self.alerts.append({
            "time": time.strftime("%H:%M:%S"),
            "message": alert_msg
        })
        
    def generate(self):
        """
        Creates a self-contained HTML report with CSS/JS.
        """
        if not self.alerts:
            # Don't generate empty reports
            return

        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>MANTIS Threat Report</title>
            <style>
                body {{ font-family: 'Segoe UI', sans-serif; background: #1a1a1a; color: #f0f0f0; margin: 0; padding: 20px; }}
                h1 {{ color: #00ff9d; border-bottom: 2px solid #00ff9d; padding-bottom: 10px; }}
                .card {{ background: #2d2d2d; border-radius: 8px; padding: 20px; margin-bottom: 20px; box-shadow: 0 4px 6px rgba(0,0,0,0.3); }}
                table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
                th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #404040; }}
                th {{ background: #333; color: #00ff9d; }}
                tr:hover {{ background: #383838; }}
                .tag {{ padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; }}
                .tag-ddos {{ background: #ff4444; color: white; }}
                .tag-scan {{ background: #ffbb33; color: black; }}
                .tag-web {{ background: #33b5e5; color: white; }}
                .tag-malware {{ background: #aa66cc; color: white; }}
                .summary-box {{ display: flex; gap: 20px; }}
                .metric {{ background: #333; padding: 15px; border-radius: 5px; flex: 1; text-align: center; }}
                .metric h3 {{ margin: 0; color: #888; font-size: 14px; }}
                .metric p {{ margin: 5px 0 0; font-size: 24px; font-weight: bold; color: white; }}
            </style>
        </head>
        <body>
            <h1>M.A.N.T.I.S. Forensic Report</h1>
            
            <div class="card">
                <h2>Session Summary</h2>
                <div class="summary-box">
                    <div class="metric">
                        <h3>Generated At</h3>
                        <p>{time.ctime()}</p>
                    </div>
                    <div class="metric">
                        <h3>Total Alerts</h3>
                        <p>{len(self.alerts)}</p>
                    </div>
                    <div class="metric">
                        <h3>System Status</h3>
                        <p style="color: #ff4444;">COMPROMISED</p>
                    </div>
                </div>
            </div>
            
            <div class="card">
                <h2>Incident Log</h2>
                <table>
                    <thead>
                        <tr>
                            <th>Time</th>
                            <th>Threat Type</th>
                            <th>Details</th>
                        </tr>
                    </thead>
                    <tbody>
        """
        
        for item in self.alerts:
            msg = item['message']
            timestamp = item['time']
            
            # Simple parsing of the alert string
            alert_type = "UNKNOWN"
            css_class = ""
            if "DDoS" in msg:
                alert_type = "DDoS Attack"
                css_class = "tag-ddos"
            elif "SCAN" in msg:
                alert_type = "Port Scan"
                css_class = "tag-scan"
            elif "PAYLOAD" in msg:
                alert_type = "Web Attack"
                css_class = "tag-web"
            elif "BLACKLIST" in msg:
                alert_type = "Blackist Hit"
                css_class = "tag-malware"
                
            row = f"""
                <tr>
                    <td>{timestamp}</td>
                    <td><span class="tag {css_class}">{alert_type}</span></td>
                    <td>{msg}</td>
                </tr>
            """
            html += row
            
        html += """
                    </tbody>
                </table>
            </div>
            
            <div class="card">
                <p>Generated by M.A.N.T.I.S. (Minimalist Alert Network for Threat Intelligence System)</p>
            </div>
        </body>
        </html>
        """
        
        with open(self.filename, "w") as f:
            f.write(html)
        print(f"\n[*] HTML Report generated: {os.path.abspath(self.filename)}")

# Test
if __name__ == "__main__":
    r = ReportGenerator()
    r.add_alert("DDoS DETECTED! Z-Score: 5.2")
    r.add_alert("PORT SCAN DETECTED! (Unique Ports: 44/sec)")
    r.add_alert("MALICIOUS PAYLOAD! Keywords: ['UNION', 'SELECT']")
    r.generate()
